PharmacyMvcClient/PharmacyMvcClient/Models/Branch.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PharmacyMvcClient.Models
{
    public class Branch
    {
        [Key]
        public int BranchID { get; set; }
        [Required,StringLength(50)]
        public string BranchName { get; set; }
        [Required,StringLength(11)]
        public string BranchPhone { get; set; }
        [Required,StringLength(100)]
        public string BranchAdress { get; set; }
        
    }
}

PharmacyMvcClient/PharmacyMvcClient/Controllers/BranchController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PharmacyMvcClient.Models;
using System.Collections.Generic;
using System.Net.Http;

namespace PharmacyMvcClient.Controllers
{
    public class BranchController : Controller
    {
        public IActionResult Index()
        {
            HttpClient client = new HttpClient();
            var responseMessage = client.GetAsync("https://localhost:44320/api/Branch").Result;
            List<Branch> branches = null;
            if (responseMessage.StatusCode == System.Net.HttpStatusCode.OK)
            {
                //DeserializeObject :json formatındaki değerleri nesneye dönüştürmeye denir.
                //SerializeObject :nesneyi json formatna çevirir.
                branches = JsonConvert.DeserializeObject<List<Branch>>(responseMessage.Content.ReadAsStringAsync().Result);
            }
            return View(branches);
        }
        public IActionResult Add()
        {
            return View(new Branch());
        }
        [HttpPost]
        public IActionResult Add(Branch branches)
        {
            HttpClient httpClient = new HttpClient();
            StringContent content = new StringContent(JsonConvert.SerializeObject(branches), System.Text.Encoding.UTF8, "application/json");
            var responseMessage = httpClient.PostAsync("https://localhost:44320/api/Branch", content).Result;
            if (responseMessage.StatusCode == System.Net.HttpStatusCode.Created)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Ekleme İşlemi Başarısız");
            return View();
        }
        public IActionResult Edit(int id)
        {
            HttpClient httpClient = new HttpClient();
            var responseMessage = httpClient.GetAsync($"https://localhost:44320/api/Branch/{id}").Result;
            if (responseMessage.StatusCode == System.Net.HttpStatusCode.OK)
            {
                var branches = JsonConvert.DeserializeObject<Branch>(responseMessage.Content.ReadAsStringAsync().Result);
                return View(branches);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Edit(Branch branches)
        {
            HttpClient httpClient = new HttpClient();
            StringContent content = new StringContent(JsonConvert.SerializeObject(branches), System.Text.Encoding.UTF8, "application/json");
            var responseMessage = httpClient.PutAsync($"https://localhost:44320/api/Branch/{branches.BranchID}", content).Result;
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            HttpClient httpClient = new HttpClient();
            var responseMessage = httpClient.DeleteAsync($"https://localhost:44320/api/Branch/{id}").Result;
            return RedirectToAction("Index");

        }
    }
}

PharmacyMvcClient/PharmacyMvcClient/Views/Branch/Add.cshtml
@using PharmacyMvcClient.Models;
@model Branch
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<html>
<head>
    <title></title>
    <link href="~/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container mt-2">
        <form asp-action="Add" asp-controller="Branch" method="post">
            <div class="form-group">
                <label>Branch Name:</label>
                <input type="text" name="BranchName" class="form-control" />
            </div>
            <div class="form-group">
                <label>Branch Phone :</label>
                <input type="text" name="BranchPhone" class="form-control" />
            </div>
            <div class="form-group">
                <label>Branch Adress :</label>
                <input type="text" name="BranchAdress" class="form-control" />
            </div>
            <div class="form-group">

                <button type="submit" class="btn-primary">Save</button>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger">
            </div>
        </form>
    </div>
</body>
</html>

PharmacyMvcClient/PharmacyMvcClient/Views/Branch/Edit.cshtml
@model PharmacyMvcClient.Models.Branch

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Edit</h1>

<h4>Branch</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BranchID" class="control-label"></label>
                <input asp-for="BranchID" class="form-control" />
                <span asp-validation-for="BranchID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BranchName" class="control-label"></label>
                <input asp-for="BranchName" class="form-control" />
                <span asp-validation-for="BranchName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BranchPhone" class="control-label"></label>
                <input asp-for="BranchPhone" class="form-control" />
                <span asp-validation-for="BranchPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BranchAdress" class="control-label"></label>
                <input asp-for="BranchAdress" class="form-control" />
                <span asp-validation-for="BranchAdress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PharmacyMvcClient/PharmacyMvcClient/Views/Branch/Index.cshtml
@using PharmacyMvcClient.Models;
@model List<Branch>
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<html>
<head>
    <title></title>
    <link href="~/twitter-bootstrap/css/
bootstrap.css" rel="stylesheet" />

    <link href="~/twitter-bootstrap/css/
bootstrap-grid.css" rel="stylesheet" />
</head>
<body>
    <div class="container mt-2">
        <div class="bg-dark text-white-50 lead text-center
my-2 p-2">
            BRANCH LİST
        </div>
        <div class=" text-right pr-2 my-2">
            @* @Html.ActionLink("Add","Sporcular",null,new{@class="btn btn-striped"})*@
            <a asp-action="Add"
               asp-controller="Branch"
               class="btn btn-primary btn-sm">Ekle</a>
        </div>
        <table class="table table-hover table-striped
table-bordered table-sm">
            @foreach (var branch in Model)
            {
                <tr>
                    <td>@branch.BranchID</td>
                    <td>@branch.BranchName</td>
                    <td>@branch.BranchPhone</td>
                    <td>@branch.BranchAdress</td>
                    <th>İşlem</th>
                    <td>
                        <a asp-action="Edit" asp-controller="Branch"
                       asp-route-id="@branch.BranchID" class="btn btn-warning btn-sm">Edit</a>
                        <a onclick="return confirm('Silmek isteğinizden emin misiniz?')"
                       asp-action="Delete" asp-controller="Branch"
                       asp-route-id="@branch.BranchID"
                       class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</body>
</html>