PharmacyMvcClient/PharmacyMvcClient/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace PharmacyMvcClient.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PharmacyMvcClient/PharmacyMvcClient/Controllers/HMedicineController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PharmacyMvcClient.Models;
using System.Collections.Generic;
using System.Net.Http;

namespace PharmacyMvcClient.Controllers
{
    public class HMedicineController : Controller
    {
        public IActionResult Index()
        {
            HttpClient client = new HttpClient();
            var responseMessage = client.GetAsync("https://localhost:44320/api/Medicine").Result;
            List<Medicine> medicines = null;
            if (responseMessage.StatusCode == System.Net.HttpStatusCode.OK)
            {
                //DeserializeObject :json formatındaki değerleri nesneye dönüştürmeye denir.
                //SerializeObject :nesneyi json formatna çevirir.
                medicines = JsonConvert.DeserializeObject<List<Medicine>>(responseMessage.Content.ReadAsStringAsync().Result);
            }
            return View(medicines);
        }
    }
}

PharmacyMvcClient/PharmacyMvcClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>İRON PHARMACY</title>
    <meta charset="utf-8"  >
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="~/hometemp/fonts/icomoon/style.css">
    <link rel="stylesheet" href="~/hometemp/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/hometemp/css/magnific-popup.css">
    <link rel="stylesheet" href="~/hometemp/css/jquery-ui.css">
    <link rel="stylesheet" href="~/hometemp/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/hometemp/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/hometemp/css/aos.css">
    <link rel="stylesheet" href="~/hometemp/css/style.css">

</head>
<body>
    <div class="site-wrap">


        <div class="site-navbar py-2">

            <div class="search-wrap">
                <div class="container">
                    <a href="#" class="search-close js-search-close"><span class="icon-close2"></span></a>
                    <form action="#" method="post">
                        <input type="text" class="form-control" placeholder="Search keyword and hit enter...">
                    </form>
                </div>
            </div>

            <div class="container">
                <div class="d-flex align-items-center justify-content-between">
                    <div class="logo">
                        <div class="site-logo">
                            <a href="index.html" class="js-logo-clone">Pharma</a>
                        </div>
                    </div>
                    <div class="main-nav d-none d-lg-block">
                        <nav class="site-navigation text-right text-md-center" role="navigation">
                            <ul class="site-menu js-clone-nav d-none d-lg-block">
                                <li class="active"><a href="@Url.Action("Index","Home")">Home</a></li>
                                <li><a href="@Url.Action("Index","HMedicine")">Medicine</a></li>
                                <li><a href="@Url.Action("About","Home")">About</a></li>
                                <li><a href="@Url.Action("Contact","Home")">Contact</a></li>
                                <li><a href="@Url.Action("Index","Admin")">Admin</a></li>

                            </ul>
                        </nav>
                    </div>
                    <div class="icons">
                        <a href="#" class="icons-btn d-inline-block js-search-open"><span class="icon-search"></span></a>
                        <a href="cart.html" class="icons-btn d-inline-block bag">
                            <span class="icon-shopping-bag"></span>
                            <span class="number">2</span>
                        </a>
                        <a href="#" class="site-menu-toggle js-menu-toggle ml-3 d-inline-block d-lg-none">
                            <span class="icon-menu"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="site-blocks-cover" style="background-image: url('../hometemp/images/hero_1.jpg');">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 mx-auto order-lg-2 align-self-center">
                        <div class="site-block-cover-content text-center">
                            <h2 class="sub-title">Effective Medicine, New Medicine Everyday</h2>
                            <h1>Welcome To Pharma</h1>
                            <p>
                                <a href="#" class="btn btn-primary px-5 py-3">Shop Now</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">

                    <div class="block-7">
                        <h3 class="footer-heading mb-4">About Us</h3>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius quae reiciendis distinctio voluptates
                            sed dolorum excepturi iure eaque, aut unde.
                        </p>
                    </div>

                </div>
                <div class="col-lg-3 mx-auto mb-5 mb-lg-0">
                    <h3 class="footer-heading mb-4">Quick Links</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Supplements</a></li>
                        <li><a href="#">Vitamins</a></li>
                        <li><a href="#">Diet &amp; Nutrition</a></li>
                        <li><a href="#">Tea &amp; Coffee</a></li>
                    </ul>
                </div>

                <div class="col-md-6 col-lg-3">
                    <div class="block-5 mb-5">
                        <h3 class="footer-heading mb-4">Contact Info</h3>
                        <ul class="list-unstyled">
                            <li class="address">203 Fake St. Mountain View, San Francisco, California, USA</li>
                            <li class="phone"><a href="tel://23923929210">+2 392 3929 210</a></li>
                            <li class="email">emailaddress@domain.com</li>
                        </ul>
                    </div>


                </div>
            </div>
            <div class="row pt-5 mt-5 text-center">
                <div class="col-md-12">
                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made
                        with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank"
                                                                                 class="text-primary">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>

            </div>
        </div>
    </footer>
    <script src="~/hometemp/js/jquery-3.3.1.min.js"></script>
    <script src="~/hometemp/js/jquery-ui.js"></script>
    <script src="~/hometemp/js/popper.min.js"></script>
    <script src="~/hometemp/js/bootstrap.min.js"></script>
    <script src="~/hometemp/js/owl.carousel.min.js"></script>
    <script src="~/hometemp/js/jquery.magnific-popup.min.js"></script>
    <script src="~/hometemp/js/aos.js"></script>
    <script src="~/hometemp/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>